### ISSUE TITLE
Why i can't name any format code

### ISSUE THREAD

**Issue by JorosTheModderPH** [IdleDevelopment/IdleyApp#2]
Why i can't name any format code just like this §
When you save,it will turn out into this /u00072/

Pls fix.

**Comment by JorosTheModderPH** [comment]
From minecraft server,wait i heard that github discord bot report my issues lol

**Comment by ghost** [comment]
> From minecraft server,wait i heard that github discord bot report my issues lol

It's a pterodactyl issue, use & instead.

**Comment by yigitkerem** [comment]
This seems totally irrelevant so I am closing this.
